# Generated by Django 4.2.17 on 2024-12-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postblog_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
