# Generated by Django 4.2.17 on 2024-12-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='postblog',
            options={'ordering': ['created_on']},
        ),
    ]
